version: '3.8'

services:
  php-apache:
    build: .
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - .:/var/www/html
      - /Users/shahriar/Sites/attendance/.env:/var/www/html/.env:ro
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
