name: CI/CD to EC2

on:
  push:
    branches:
      - main

      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 'main' branch
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip

    - name: Set up SSH key permissions
      run: |
        echo "$EC2_SSH_KEY" > ssh_key.pem
        chmod 600 ssh_key.pem
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

    - name: Prepare and Deploy
      run: |
        set -e
        set -x

        mkdir .attendance
        echo "copy start"
        cp -r * .attendance
        echo "copy end, move start"
        mv .attendance attendance
        echo "zip start"
        zip -r attendance.zip attendance
        echo "zip end"


        scp -o StrictHostKeyChecking=no -i ssh_key.pem attendance.zip ${{secrets.EC2_USERNAME}}@${{secrets.EC2_HOST}}:/var/www/html

        ssh -o StrictHostKeyChecking=no -i ssh_key.pem ${{secrets.EC2_USERNAME}}@${{secrets.EC2_HOST}} "cd /var/www/html && unzip -o attendance.zip"



        echo "Application successfully deployed."

    - name: Clean up
      run: rm -rf attendance attendance.zip ssh_key.pem
