name: CI/CD to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 'main' branch
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip

    - name: Set up SSH key permissions
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > ssh_key.pem
        chmod 600 ssh_key.pem

    - name: Test SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no -i ssh_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "echo Connected successfully"
 
    - name: Prepare and Deploy
      run: |
        set -e
        set -x

        mkdir .attendance
        cp -r * .attendance
        mv .attendance attendance
        zip -r attendance.zip attendance

        scp -o StrictHostKeyChecking=no -i ssh_key.pem attendance.zip ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/var/www/html

        ssh -o StrictHostKeyChecking=no -i ssh_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd /var/www/html && unzip -o attendance.zip"

    - name: Clean up
      run: rm -rf attendance attendance.zip ssh_key.pem
